apiVersion: v1
kind: Service
metadata:
  name: ${DEPLOYMENT_NAME}
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
  ports:
    - port: ${KEYCLOAK_PORT}
      targetPort: ${DOCKER_INTERNAL_PORT}
      nodePort: ${KEYCLOAK_NODE_PORT}
